resolves #2
cichan02/micro-airport-core pull request #4
Opened 2023-03-13 07:48 UTC by cichan02

2023-03-13 10:49 UTC, h1alexbel commented
@cichan02 resolve the merge conflict

2023-03-13 12:20 UTC, h1alexbel approved these changes

2023-03-13 12:21 UTC, h1alexbel commented
@cichan02 please resolve merge conflicts

2023-03-13 12:23 UTC, cichan02 commented
@h1alexbel fixes merge conflict

2023-03-13 12:56 UTC, h1alexbel requested changes

2023-03-14 12:58 UTC, h1alexbel approved these changes

2023-03-14 12:58 UTC, merged